---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: demo
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.chart-image: semver:~5.0
    fluxcd.io/locked: 'false'
    fluxcd.io/locked_msg: 'Update open again'
    fluxcd.io/locked_user: 'Chris Smith <chris.b.smith@gmail.com>'
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 9.5.2
  valueFileSecrets:
    # the redis-auth secret contains the password value
  - name: redis-auth
  values:
    usePassword: true
    image:
      repository: bitnami/redis
      tag: 5.0.6
    service:
      type: ClusterIP
      port: 6379
    cluster:
      enabled: false
    master:
      securityContext:
        enabled: false
        fsGroup: 0
        runAsUser: 0
      persistence:
        enabled: false
